### PR TITLE
Optional sound system

### LINKED ISSUE #6515: [OpenAL] Wrong exception type when binaries are missing
Hey there,

Even if none of the ```Audio``` namespace is used, MonoGame initialize the static ```OpenAL``` bindings and tries to load the library and its entry points, resulting in a ```EntryPointNotFoundException``` if the OpenAL binaries are missing.

This is an issue when using third party sound engines and not shipping the OpenAL binaries.

Please also note that this is broken: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/SDL/SDLGamePlatform.cs#L72

The ```DllNotFoundException``` is no more triggered because the entry points loading have changed and are now throwing ```EntryPointNotFoundException```. And even if ```GetNativeLibrary()``` would throw the correct exception type, this code won't be triggered because it happens in the static initializer and no more within the ```OpenALSoundController``` constructor.

Related to #6107 and #4717

I think we should move forward with making the ```Audio``` namespace and its dependencies fully optional.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- All

#### What MonoGame platform are you using:

- DesktopGL

### PR DESCRIPTION
**Pull request by mrhelmut**
Hey there,

This PR should make ```Microsoft.Xna.Framework.Media``` and ```Microsoft.Xna.Framework.Audio``` optional so that no sound system is initialized if none of those namespace are used. This should make MonoGame friendly to third party sound engine like FMOD or Wwise.

It addresses:
- #6515 exception types are now consistent (it's either ```DllNotFoundException``` or ```NoAudioHardwareException```)
- #6107 if no ```SoundEffect``` ```Song``` ```MediaPlayer``` ```Microphone``` or ```DynamicSoundEffectInstance``` are used, OpenAL won't get loaded and the dll can be removed from release packages
- #4717 this error can now be caught through ```SoundEffect.Initialize()``` and developers can make it so it is not fatal

As suggested previously, sound engine initialization is now done whenever ```SoundEffect``` ```Song``` ```MediaPlayer``` ```Microphone``` or ```DynamicSoundEffectInstance``` are constructed.
It is however possible to manually initialize the ```SoundEffect``` API by calling ```SoundEffect.Initialize()```. This allows developers to get any initialization errors and act accordingly (e.g. disabling sound, or make it fatal).

Fixes #6515 #6107 #4717

@Jjagg @cra0zy 
@tomspilman if this goes through, I'll try to get the console repos' compliant.

### CODE REVIEW

File: MonoGame.Framework/Audio/OpenALSoundController.cs [hunk 1]
```diff
@@ -291,8 +290,25 @@ public static OpenALSoundController GetInstance
         {
 			get
             {
-				if (_instance == null)
-					_instance = new OpenALSoundController();
+                if (_instance == null)
+                {
+                    try
```
Comment (Jjagg) [inline MonoGame.Framework/Audio/OpenALSoundController.cs]: This `GetInstance` property doesn't really make sense to me, at least with this naming. Should be a method IMO.
Also would make more sense to be able to call an initialize function instead of this to initialize OpenAL. Can you extract the code here into an `EnsureInitialized` function:

```
public static void EnsureInitialized()
{
    if (_instance ~= null)
        return;
    try
    {
    ...
}

public static OpenALSoundController GetInstance()
{
    EnsureInitialized();
   return _instance;
}
```

File: MonoGame.Framework/Audio/SoundEffect.OpenAL.cs [hunk 2]
```diff
@@ -235,17 +235,9 @@ private void PlatformDispose(bool disposing)
...
-            try
-            {
-                // Getting the instance for the first time initializes OpenAL
-                var oal = OpenALSoundController.GetInstance;
-            }
-            catch (DllNotFoundException ex)
-            {
-                throw new NoAudioHardwareException("Failed to init OpenALSoundController", ex);
-            }
+            var inst = OpenALSoundController.GetInstance;
```
Comment (Jjagg) [inline MonoGame.Framework/Audio/SoundEffect.OpenAL.cs]: This should call OpenALSoundController.EnsureInitialized().

File: MonoGame.Framework/Audio/SoundEffect.cs [hunk 3]
```diff
@@ -63,7 +71,11 @@ internal SoundEffect(byte[] header, byte[] buffer, int bufferSize, int durationM
 
         // Only used from XACT WaveBank.
         internal SoundEffect(MiniFormatTag codec, byte[] buffer, int channels, int sampleRate, int blockAlignment, int loopStart, int loopLength)
-        {
+        {
+            Initialize();
+            if (_systemState != SoundSystemState.Initialized)
```
Comment (Jjagg) [inline MonoGame.Framework/Audio/SoundEffect.cs]: These should maybe throw?

File: MonoGame.Framework/Media/Song.NVorbis.cs [hunk 4]
```diff
@@ -16,6 +16,9 @@ public sealed partial class Song : IEquatable<Song>, IDisposable
 
         private void PlatformInitialize(string fileName)
         {
+            // init OpenAL if need be
+            var inst = OpenALSoundController.GetInstance;
```
Comment (Jjagg) [inline MonoGame.Framework/Media/Song.NVorbis.cs]: Should call OpenALSoundController.EnsureInitialized() too.

File: MonoGame.Framework/Audio/OpenALSoundController.cs (hunk 1 above)
Comment (mrhelmut) [reply MonoGame.Framework/Audio/OpenALSoundController.cs]: Yeah, this GetInstance has been there for a long time and has been used to initialize stuff at several places...

I think we should turn it into a property and make it throw if it is called before the initialization, so that the code the more readable with no hidden initialization due to a property accessor.

**Comment by mrhelmut** [comment]
Thanks! I'm going to refactor the controller instance management, it has been a bit messy for quite too long.

File: MonoGame.Framework/Audio/OpenALSoundController.cs (hunk 1 above)
Comment (Jjagg) [reply MonoGame.Framework/Audio/OpenALSoundController.cs]: > I think we should turn it into a property and make it throw if it is called before the initialization, so that the code is more readable with no hidden initialization due to a property accessor.

 Even better

File: MonoGame.Framework/Audio/SoundEffect.cs (hunk 3 above)
Comment (mrhelmut) [reply MonoGame.Framework/Audio/SoundEffect.cs]: I believe there are not even useful since Initialize() throws.

**Comment by mrhelmut** [comment]
@Jjagg I think I got things clean up. Let me know how it goes for you.

**Comment by mrhelmut** [comment]
Ready for review.

**Comment by Jjagg** [comment]
Looks good to me! Gonna hold off a little bit in case anyone else wants to go over this, but will merge if not.

File: MonoGame.Framework/Audio/Microphone.cs [hunk 5]
```diff
@@ -128,7 +129,7 @@ public static ReadOnlyCollection<Microphone> All
         /// </summary>
         public static Microphone Default
         {
-            get { return _default; }
```
Comment (cra0zy) [inline MonoGame.Framework/Audio/Microphone.cs]: Write code like this in the static initializer instead of static property.

File: MonoGame.Framework/Audio/Microphone.cs [hunk 6]
```diff
@@ -128,7 +129,7 @@ public static ReadOnlyCollection<Microphone> All
...
+            get { SoundEffect.Initialize(); return _default; }
```
Comment (cra0zy) [inline MonoGame.Framework/Audio/Microphone.cs]: Write code like this in the static initializer instead of static property.

Comment (cra0zy) [reply MonoGame.Framework/Audio/Microphone.cs]: Just so there is no confusion, ie:

```c#
static Microphone()
{
    SoundEffect.Initialize();
}
```

Comment (cra0zy) [reply MonoGame.Framework/Audio/Microphone.cs]: You could also use static constructors in few other places.

Comment (Jjagg) [reply MonoGame.Framework/Audio/Microphone.cs]: I think it's better to check if initialization was done properly on every call, rather than do it only once. It makes behavior more predictable. Static initializers complicate control flow because you can't be sure when they'll be called.

Comment (cra0zy) [reply MonoGame.Framework/Audio/Microphone.cs]: They get called during first access to their respective class.

Comment (Jjagg) [reply MonoGame.Framework/Audio/Microphone.cs]: Yes, I mean we don't control when it's called.

Comment (mrhelmut) [reply MonoGame.Framework/Audio/Microphone.cs]: The thing is, ```Default``` and ```All`` are the microphone entry points, but you have to initialize the sound API to populate the microphones, and the Microphone class is static by design...
Unless we change the design of the Microphone class, I don't think we can do anything else than having this in a static field. I'm not a fan of static classes because this kind of design problems.

Alternative proposition: not initializing the sound API at all in the Microphone class, and throw if All/Default are accessed while not initialized. Forcing users to either call ```SoundEffect.Initialize()``` or to use the auto initialization when loading content.

I've seen static classes initializing without obvious calls to them, so I'd feel more comfortable with not having any library loading happening inside static ctor/fields.

For the same reason, I don't quite like ```OpenAL.NativeLibrary``` being initialized statically. I think I'm going to change that too.

Comment (Jjagg) [reply MonoGame.Framework/Audio/Microphone.cs]: We should not change the API by forcing explicit initialization. If we could have a fresh API, I'd definitely want to make it explicit though.

Comment (cra0zy) [reply MonoGame.Framework/Audio/Microphone.cs]: How about just checking if Audio systems can be initialized on game run?

> For the same reason, I don't quite like OpenAL.NativeLibrary being initialized statically. I think I'm going to change that too.

Please don't, those are just wrappers. Think of them as `DllImport` statements :P

Comment (mrhelmut) [reply MonoGame.Framework/Audio/Microphone.cs]: Sure, but they do load the dll if the static ctor kicks in, which we want to avoid to not mess up with third party sound engine.

But if we can't get the sound api to initialize in a non static way for Microphone, there's no point in removing the static initialization from OpenAL anyway because it'll still be around within Microphone.

**Comment by mrhelmut** [comment]
I think we have to take a stance regarding static initialization.

Option 1) Leave it be, and 100% trust the runtime to not initialize static classes unless they are used. Move Microphone initialization to a static ctor.

Option 2) Don't trust the runtime. Move all OpenAL function loading outside of the static initialization.

I'm in favor of 2), so that we have a control over when and how OpenAL gets loaded.

File: MonoGame.Framework/Audio/Microphone.cs (hunk 6 above)
Comment (mrhelmut) [reply MonoGame.Framework/Audio/Microphone.cs]: I am more suspicious of Microphone than I am of OpenAL. I'd prefer to not add a static constructor to Microphone.

If we'd like to be 100% safe, I'd suggest to move static initialization out of OpenAL func loading and manually load them (to have a perfect control on the "when" and "how").

**Comment by mrhelmut** [comment]
After giving some thoughts about static initializers, I believe that we are 100% fine with ```OpenAL``` statically loading the binary. I assume that people not willing to use OpenAL will remove the dll from their distribution, which doesn't trigger any error if OpenAL tries to load anyway (unless ```SoundEffect.Initialize()``` is called, but then it's the expected behavior).

I am however not in favor of having ```Microphone``` use a static initializer to initialize the sound API. As of now everything would be fine, but we have no control over what could reference Microphone and possibly trigger its initializer. For safety, I prefer to have the initialization upon accessing the microphones list.

@Jjagg @cra0zy What do you think? If it's ok to you, then it should be good to go.

**Comment by Jjagg** [comment]
That's fine by me.

**Comment by mrhelmut** [comment]
@cra0zy Could you share your thoughts about the current status of this PR? It would be cool to move forward.

I've been running on this PR for quite time now, using FMOD.

**Comment by cra0zy** [comment]
Looks fine to me, sorry for the delay.

**Comment by Jjagg** [comment]
Thanks @mrhelmut! Merging this :D
