### PR TITLE
Pipeline process not terminating on exit fix

### LINKED ISSUE #5439: Pipeline tool process stays active after exiting
Hello,

When closing the Pipeline tool (at least on Windows), the window closes correctly but the process remains active and takes 100% of a CPU core usage.

### PR DESCRIPTION
**Pull request by zigzag312**
Fixes #5439

### CODE REVIEW

File: Tools/Pipeline/Common/PipelineController.FileWatcher.cs [hunk 1]
```diff
@@ -60,6 +61,10 @@ private void ExistsThread()
                             _view.Invoke(() => _view.UpdateTreeItem(item));
                         }
                     }
+                    catch (ThreadAbortException ex)
+                    {
+                        loop = false;
```
Comment (cra0zy) [inline Tools/Pipeline/Common/PipelineController.FileWatcher.cs]: You should just call `return` instead of adding unnecessary variable.

Comment (zigzag312) [inline Tools/Pipeline/Common/PipelineController.FileWatcher.cs]: I've simplified this as you suggested

**Comment by tomspilman** [comment]
Thanks @zigzag312 !
