### PR TITLE
Fixes to switching away from exclusive full-screen

### LINKED ISSUE #5885: Fullscreen + Alt Tab still an issue in latest MonoGame 3.7.0.753 Development build
I put together a video that shows the issue is still persisting. I saw that the latest dev build had some fixes committed 4 days ago for this issue, but it appears to persist at least on my box. 

VIDEO: https://youtu.be/1hT_YOruTdk

Machine:
1) Windows 10, 64-bit, Latest Update Pack installed as of 8/19/2017
2) NVIDIA

Steps taken to reproduce :
1) Uninstalled Monogame v3.7.0.744
2) Installed Monogame v3.7.0.753
3) Cleaned the projects
4) Rebuilt
5) Run the game in FULLSCREEN mode
6) ALT-TAB out to the desktop

Result:
1) Game icon is not visible on the task bar.
2) The game is still running as a background process (interestingly enough, OBS was still able to capture it!)
3) Holding down ALT-TAB also shows that the game process is not accessible
4) I have to End Task from the task manager to shut the game down.

Thoughts?

### PR DESCRIPTION
**Pull request by KonajuGames**
Fixes DirectX switching away from exclusive full-screen mode by forcing the swapchain out of exclusive mode and minimizing the window.
Fixes OpenGL switching away from exclusive full-screen mode by enabling the SDL hint to minimize video on loss of focus when changing to exclusive full-screen mode, otherwise the hint is left disabled.

Fixes #5885

### CODE REVIEW

File: MonoGame.Framework/SDL/SDLGameWindow.cs [hunk 1]
```diff
@@ -218,6 +218,8 @@ public override void EndScreenDeviceChange(string screenDeviceName, int clientWi
                 Sdl.Window.SetFullscreen(Handle, (_willBeFullScreen) ? fullscreenFlag : 0);
                 _hardwareSwitch = _game.graphicsDeviceManager.HardwareModeSwitch;
             }
+            // If going to exclusive full-screen mode, force the window to minimize on focus loss
+            Sdl.SetHint("SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS", _willBeFullScreen && _hardwareSwitch ? "1" : "0");
```
Comment (cra0zy) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: This will cause problems on multimonitor setups, especially on Linux.

Comment (KonajuGames) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: It was tested on my multi-monitor setup here on Windows and works as it should.  Previously it did not remove the window at all, leaving that monitor useless.  If it causes issues on multi-monitor setups on Linux, then they can be fixed later because this is a major issue on Windows right now.

Comment (cra0zy) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: Add a conditional to only apply that to Windows, on Linux I can just manually minimize the game and I get the resolution back to the original.

Comment (tomspilman) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: > then they can be fixed later

I agree.

> Add a conditional to only apply that to Windows,

If we do this use the runtime conditional here, so that one binary that works on Win/Mac/Linux still works.

Comment (cra0zy) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: > If we do this use the runtime conditional here, so that one binary that works on Win/Mac/Linux still works.

Talking about:
```c#
if (CurrentPlatform.OS == OS.Windows)
{
   // Do Stuff
}
```

Comment (cra0zy) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/CurrentPlatform.cs

Comment (KonajuGames) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: How does Mac handle this? Do we have to make an exemption for Mac as well?

**Comment by KonajuGames** [comment]
Exemption for Linux and Mac added.

File: MonoGame.Framework/SDL/SDLGameWindow.cs (hunk 1 above)
Comment (cra0zy) [inline MonoGame.Framework/SDL/SDLGameWindow.cs]: IDK how Mac handles it. someone should probably test it out.

**Comment by tomspilman** [comment]
Thanks @KonajuGames ... merging!
