### PR TITLE
Fixes and XNA compliance for GraphicsDeviceManager and GraphicsDevice

### LINKED ISSUE #539: Render to texture: RenderTargetUsage.PreserveContents ignored
Hey,
OS: Linux
I do not exactly know how this feature works, but in many tutorials, the following can be found.
1:  React to the this event in your Game class:
OnPreparingDeviceSettings(Object sender, PreparingDeviceSettingsEventArgs e)
by doing this in the constructor:
mGraphicsDeviceManager.PreparingDeviceSettings += OnPreparingDeviceSettings;

2: Set e.GraphicsDeviceInformation.PresentationParameters.RenderTargetUsage = RenderTargetUsage.PreserveContents;

When you now change the render target with RenderTargetUsage.PreserveContents as the last parameter, the contents of the old render target will not be lost. This allows for render-to-texture code between other rendering-code without getting a purple screen.
MonoGame does not even call OnPreparingDeviceSettings and therefore ignores RenderTargetUsage.PreserveContents.

### LINKED ISSUE #3114: graphicsdevicemanager.disposed not implemented
http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphicsdevicemanager.disposed.aspx

Is not implemented

Its not a major part of our code but we have found that logging Device and DeviceManager events into our debugging logs really can help detect issues when you release on PC - there's so many things that can go wrong that clues like these events firing can help

### LINKED ISSUE #4433: Refactor GraphicsDevice.PresentationParameters
Doing some experimenting against XNA for #4425 I found that our implementation of `GraphicsDevice.PresentationParameters` is wrong.

`GraphicsDevice.PresentationParameters` is only the output presentation values representing the state of the `GraphicsDevice` the last time the presentation was changed.

This means `GraphicsDeviceManager` shouldn't be making changes to it directly.  Instead `GraphicsDeviceManager` should be creating a new `PresentationParameters` object... populating it with the new state... then passing that to `GraphicsDeviceManager` to become the new presentation state.

Some code that currently fails under MonoGame:

```
var oldpp = GraphicsDevice.PresentationParameters;
GraphicsDeviceManager.PreferredBackBufferWidth = 100;
GraphicsDeviceManager.ApplyChanges();
var newpp = GraphicsDevice.PresentationParameters; 
Debug.Assert(!object.ReferenceEquals(oldpp, newpp));
```

### LINKED ISSUE #4740: Windows DX: Window is not centred on startup
When using Windows DirectX, the game window is no longer centred on start up. Windows GL still works correctly.

Does anyone have any ideas on what might have broken this? If not, I will try take a look into this later when I have time.

### LINKED ISSUE #5173: [DX] Calling ApplyChanges() in Game actor cause Exception
Seen on W8.1 but probably also an issue on other Windows/DX. 

If we call graphics.ApplyChanges() inside the Game constructor it has no effect on XNA and MG 3.5. It was most likely ignored.
With the latest develop build we get an error later inside Initialize()
[System.Runtime.InteropServices.COMException] = {System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.}
message: "DCOMPOSITION_ERROR_WINDOW_ALREADY_COMPOSED\r\n"

The problem is this line https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GraphicsDeviceManager.cs#L233
it used to be `return;` before https://github.com/MonoGame/MonoGame/commit/18d552abde4ef1c6351f3d884369bcecdf56372c

### PR DESCRIPTION
**Pull request by Jjagg**
This replaces #5069 because I messed up something. Sorry for the inconvenience!

This is a start to getting GraphicsDevice and GraphicsDeviceManager events right and handling PresentationParameters the same as in XNA.
- fixes #539
- fixes #4433
- fixes #3114
- fixes #4740 
- fixes #5173 
- helps with #3572 (DirectX only)

### CODE REVIEW

**Comment by Jjagg** [comment]
Might be good to get this reviewed and merged at this point. Just so it doesn't get too big and takes a long time to get reviewed properly. I'll continue with this in a new PR if that's fine @tomspilman

File: MonoGame.Framework/GraphicsDeviceManager.cs [hunk 1]
```diff
@@ -171,12 +171,13 @@ protected void OnDeviceDisposing(EventArgs e)
             Raise(DeviceDisposing, e);
         }
 
-        protected void OnDeviceResetting(EventArgs e)
+        // TODO these should be made protected, but currently WP calls these in SurfaceUpdateHandler
```
Comment (nkast) [inline MonoGame.Framework/GraphicsDeviceManager.cs]: we can make them `internal`

Comment (Jjagg) [inline MonoGame.Framework/GraphicsDeviceManager.cs]: Oh, my bad! I changed these to be protected to see where it was needed and the build didn't immediately fail (because I wasn't building WP), and when I did notice the fail I incorrectly changed them to public in stead of back to internal. Thanks! Did you have a chance to review the rest of this too? I think the easiest way is to focus on the tests I added and check if they are all decent since I basically did test-driven development. The workflow for this PR was to

1. Find issues (here on GitHub) related to GraphicsDeviceManager or come up with things that might be issues
2. write tests against XNA on this behavior and if they failed try something else and retest until they passed (so until I found the XNA behavior)
3. Check if they pass in MG and if not apply proper fixes until they did.

So checking the tests should cover most of it. I may have done some small things that were not based on a test here and there, but I can't really remember :p 

I think I can get around to fixing your remark and the conflicts tomorrow.

Comment (nkast) [inline MonoGame.Framework/GraphicsDeviceManager.cs]: > Find issues (here on GitHub) related to GraphicsDeviceManager or come up with things that might be issues

One issue I found recently is https://github.com/MonoGame/MonoGame/issues/5173.

Also WP8.0 with `DrawingSurfaceBackgroundGrid` fails to initialize because now `BackBufferWidth`/`BackBufferHeight` is set to zero. One solution is to overwrite them with values from `WindowsPhoneGameWindow.Width`/`WindowsPhoneGameWindow.Heigth`. 
https://github.com/nkast/MonoGame/blob/7ad344d3eeb378bbd7429026f59c8857fea96e70/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L226-L228

There are a couple of other issues with WP8's GraphicsDevice but never made a proper PR, I figure they most probably be noise until the platform is dropped. Anyways, FYI: 

This is wrong. `DrawingSurface`, the default in templates, support both Portrait/Landscape. https://github.com/MonoGame/MonoGame/issues/2332
https://github.com/nkast/MonoGame/blob/7ad344d3eeb378bbd7429026f59c8857fea96e70/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L223-L224 
I would say it's also unnecessary for `DrawingSurfaceBackgroundGrid` as well.(https://github.com/MonoGame/MonoGame/pull/2900) 

This code crashes when used with `DrawingSurfaceBackgroundGrid`.
https://github.com/MonoGame/MonoGame/blob/41f0761e1dff502e64ad02aa6bdb5d0839d8c8b2/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L158-L163
Something that works is 
https://github.com/nkast/MonoGame/blob/7ad344d3eeb378bbd7429026f59c8857fea96e70/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L158-L165

**Comment by tomspilman** [comment]
@Jjagg - This PR is conflicted now... if you can merge/rebase the latest develop branch that would help.

Is anything @nkast brought up that needs to be addressed here?

**Comment by Jjagg** [comment]
@nkast Can you do a seperate PR for the WP stuff? I can't test WP and it also doesn't really belong in this PR. Seeing as you have a branch with the fixes it should be easy to set up. 
I'll rebase this now :)

**Comment by nkast** [comment]
@Jjagg 
> Seeing as you have a branch with the fixes it should be easy to set up. 

That branch is more like a patch for my needs, it doesn't work with DrawingSurface at the moment. I could probably spent some time to provide a proper fix if needed.

@tomspilman 
I am under the impression that WP8.0 target will be removed at next release. For instance, #3725 skipped 3.5 and I am ok to withdraw it.

**Comment by Jjagg** [comment]
@tomspilman Not sure what's causing the crash here. Build server issues? Or is this missing some recent update to XS6 and should I just rebase?

**Comment by tomspilman** [comment]
>  Or is this missing some recent update to XS6 and should I just rebase?

Yep... rebase or merge the latest from the develop branch.

**Comment by Jjagg** [comment]
@tomspilman This should be good to go.

**Comment by Jjagg** [comment]
Bump @tomspilman @KonajuGames

**Comment by Jjagg** [comment]
@tomspilman @KonajuGames I have a branch built on this that greatly optimizes Graphics tests. Total testing time locally went from ~1:10 to 0:38. Graphics testing time went from 37 seconds to 7. I did two things to accomplish the improvement.

1. Make one GraphicsDevice and reset it's state manually instead of creating a new one every test. Only reset when necessary.
2. Don't always capture the whole backbuffer, this makes comparing captured frames way faster.

We'd have to get this in first though.

**Comment by KonajuGames** [comment]
Merging.  Thanks @Jjagg
