### PR TITLE
Fix ContentManager absolute path handling for image files

### LINKED ISSUE #8786: ContentManager inconsistent handling of absolute paths for image files vs XNB files
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

Monogame 3.8.3

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows

### Description

The `ContentManager` has functionality for loading image files (.png, .jpg, etc) when the `assetName` given is to load a `Texture2D` but there is not an XNB file.  This can be found here:

https://github.com/MonoGame/MonoGame/blob/9a986330bc3a5966c7a620ec075355fc20523c68/MonoGame.Framework/Content/ContentManager.cs#L456-L492

When the `ContentManager.RootDirectory` is set to an absolute path (which is common in scenarios where a third party editor tool is created), the following inconsistencies occur

- **XNB Files**: Load correctly due to absolute path handling in `OpenStream()`

https://github.com/MonoGame/MonoGame/blob/9a986330bc3a5966c7a620ec075355fc20523c68/MonoGame.Framework/Content/ContentManager.cs#L390-L398

- **Image Files**: Fail to load because `LoadTexture2DFromImageFile()` always uses `TitleContainerOpenStreamNoException()` which rejects absolute paths

https://github.com/MonoGame/MonoGame/blob/9a986330bc3a5966c7a620ec075355fc20523c68/MonoGame.Framework/Content/ContentManager.cs#L562-L583

https://github.com/MonoGame/MonoGame/blob/9a986330bc3a5966c7a620ec075355fc20523c68/MonoGame.Framework/TitleContainer.cs#L69-L75

### Proposed Solution

Update `LoadTexture2DFromImageFile()` to handle absolute paths the same way `OpenStream()` does:

```cs
internal Texture2D LoadTexture2DFromImageFile(string assetName)
{
    IGraphicsDeviceService graphicsDeviceService = serviceProvider.GetService(typeof(IGraphicsDeviceService)) as IGraphicsDeviceService;

    foreach (string extension in supportedTexture2DExtensions)
    {
        string assetPath = Path.Combine(RootDirectory, assetName);
        assetPath = Path.ChangeExtension(assetPath, extension);

        Stream stream = null;

        // Handle absolute paths the same way as XNB loading
#if DESKTOPGL || WINDOWS
        if (Path.IsPathRooted(assetPath))
            stream = File.OpenRead(assetPath);
        else
#endif
        stream = TitleContainer.OpenStreamNoException(assetPath);
#if ANDROID
        // Read the asset into memory in one go. This results in a ~50% reduction
        // in load times on Android due to slow Android asset streams.
        MemoryStream memStream = new MemoryStream();
        stream.CopyTo(memStream);
        memStream.Seek(0, SeekOrigin.Begin);
        stream.Close();
        stream = memStream; 
#endif

        if (stream != null)
        {
            using (stream)
            {
                Texture2D result = Texture2D.FromStream(graphicsDeviceService.GraphicsDevice, stream);
                return result;
            }
        }
    }

    return null;
}
```

### Steps to Reproduce

1. Create a new MonoGame DesktopGL project
2. Set the `ContentManager.RootDirectory` in `Game1.cs` to an absolute path (e.g `"C:\\SharedAssets\\"`)
3.Place a PNG file in that directory (e.g. `circle.png`)
4. Try to load it using `contentManager.Load<Texture2D>("circle");`

### Minimal Example Repo

_No response_

### Expected Behavior

Image files should load from absolute paths just like XNB files do

### Resulting Behavior

Image file loading fails with `ContentLoadException: "Could not load [assetName] asset!"` because `TitleContainer.OpenStreamNoException()` returns `null` for absolute paths.

### Files

Attached is a minimal reproduction.

Place the `circle.png` file first in `C:\dev` which is what the root directory for the content manager is set to. You will get the exception.

Then replace it with `circle.xnb` and you will not get the exception.

[ContentTest.zip](https://github.com/user-attachments/files/20466411/ContentTest.zip)

### PR DESCRIPTION
**Pull request by AristurtleDev**
Fixes #8786 

## Problem

The `ContentManager` has inconsistent behavior when handling absolute paths for loading XNB files versus image files. When `ContentManager.RootDirectory` is set to an absolute path (common in editor scenarios), XNB files load correctly but image files fail because `LoadTexture2DFromImageFile()` always uses `TitleContainer.OpenStreamNoException()` which rejects absolute paths.

## Solution

This PR updates `LoadTexture2DFromImageFile()` to handle absolute paths the same way as `OpenStream()` does for XNB files:

- Use `File.OpenRead()` for absolute paths on DESKTOPGL/WINDOWS platforms
- Fall back to `TitleContainer.OpenStreamNoException()` for relative paths
- Maintain existing Android memory stream optimization for consistency

## Changes

- Modified `ContentManager.LoadTexture2DFromImageFile()` to check for absolute paths using `Path.IsPathRooted()`
- Added conditional compilation directives to match existing XNB loading behavior
- Preserved all existing functionality for relative paths and Android optimization

## Testing

- Verified with the minimal reproduction case from the issue
- XNB files continue to work as before
- PNG/JPG/BMP files now load correctly from absolute paths
- Relative path loading remains unchanged

This enables editor tools and applications that need to load assets from arbitrary directories using absolute paths, matching the documented behavior that "Setting the RootDirectory to an absolute path is useful in editor situations".

### CODE REVIEW

File: MonoGame.Framework/Content/ContentManager.cs [hunk 1]
```diff
@@ -558,22 +558,40 @@ internal bool ImageFileExists(string assetName)
...
+                if (Path.IsPathRooted(assetPath))
+                    stream = File.OpenRead(assetPath);
+                else
+#endif
+                stream = TitleContainer.OpenStreamNoException(assetPath);
+#if ANDROID
+                // Read the asset into memory in one go. This results in a ~50% reduction
+                // in load times on Android due to slow Android asset streams.
+                MemoryStream memStream = new MemoryStream();
+                stream.CopyTo(memStream);
```
Comment (dellis1972) [inline MonoGame.Framework/Content/ContentManager.cs:584]: This will produce a Null Reference Exception (NRE) if TitleContainer returns null? Should we handle that state with a better error message than a standard NRE?

I have also been wondering if the code for buffering android should be moved into TitleContainer itself, as its been done in two places now. Kni uses BufferedStream see https://github.com/kniEngine/kni/blob/092c18931bc2fb15039baec0fdd02be3b90b71b8/Platforms/Content/.Android/ConcreteTitleContainer.cs#L27

Comment (AristurtleDev) [reply MonoGame.Framework/Content/ContentManager.cs:584]: > This will produce a Null Reference Exception (NRE) if TitleContainer returns null? Should we handle that state with a better error message than a standard NRE?

This is the call from within the `LoadTexture2DFromImageFile` method, which is only called from within the `try/catch` block in `ReadAsset<T>` at

https://github.com/MonoGame/MonoGame/blob/e3938b06860dbee50db9fae5e148799e735e2286/MonoGame.Framework/Content/ContentManager.cs#L426-L492

Specifically it is called at L470 within a `try/catch` that's nested within another `try/catch` so the NRE exception is caught if `TitleContainer` returns null and gives the exception on L480

https://github.com/MonoGame/MonoGame/blob/e3938b06860dbee50db9fae5e148799e735e2286/MonoGame.Framework/Content/ContentManager.cs#L480


> I have also been wondering if the code for buffering android should be moved into TitleContainer itself, as its been done in two places now. Kni uses BufferedStream see https://github.com/kniEngine/kni/blob/092c18931bc2fb15039baec0fdd02be3b90b71b8/Platforms/Content/.Android/ConcreteTitleContainer.cs#L27

To not duplicate code this would probably be ideal, I can adjust this PR to move it there or I can do a new PR for that specifically if needed

**Review by dellis1972 — APPROVED** [review]

File: MonoGame.Framework/Content/ContentManager.cs (hunk 1 above)
Comment (ThomasFOG) [reply MonoGame.Framework/Content/ContentManager.cs:584]: Note that BufferedStream is a .NET 5+ thing.

Comment (dellis1972) [reply MonoGame.Framework/Content/ContentManager.cs:584]: This would only be on the Android Path which is .net 5+

**Comment by ThomasFOG** [comment]
@SimonDarksideJ We now have a regression. See my pending review.
