### PR TITLE
Make Game.Exit set a flag to exit at the end of the tick.

### LINKED ISSUE #5127: Exit doesn't really quit game after being called
Calling Exit as this:

```
if (Keyboard.GetState().IsKeyDown(Keys.Escape))
            {
                this.Exit();
            }
```

in the beginning of update (I believe this is a fair way to do it, isn't it ?)
just do:

```
Platform.Exit();
 _suppressDraw = true;
```

and on windows DX (at least) leads to:

```
if (_window != null)
                _window.Dispose();
            _window = null;
            Window = null;
```

so in the game Update method, if window is used AFTER the call to exit like with something like this:

```
if (!IsMouseVisible)
                Mouse.SetPosition(200, 200);
```

Lead to an error as window instance has been disposed before:

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=La référence d'objet n'est pas définie à une instance d'un objet.
  Source=MonoGame.Framework
  StackTrace:
       à Microsoft.Xna.Framework.Input.Mouse.PlatformSetPosition(Int32 x, Int32 y) dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Input\Mouse.Windows.cs:ligne 34
       à Microsoft.Xna.Framework.Input.Mouse.SetPosition(Int32 x, Int32 y) dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Input\Mouse.cs:ligne 66
       à OldStyleScale.OldScale.Update(GameTime gameTime) dans C:\dev\OldStyleScale\OldScale.cs:ligne 107
       à Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Game.cs:ligne 657
       à Microsoft.Xna.Framework.Game.Tick() dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Game.cs:ligne 461
       à MonoGame.Framework.WinFormsGameWindow.RunLoop() dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Windows\WinFormsGameWindow.cs:ligne 409
       à MonoGame.Framework.WinFormsGamePlatform.RunLoop() dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Windows\WinFormsGamePlatform.cs:ligne 70
       à Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Game.cs:ligne 397
       à Microsoft.Xna.Framework.Game.Run() dans C:\MonoGame-develop\MonoGame\MonoGame.Framework\Game.cs:ligne 370
       à OldStyleScale.Program.Main(String[] args) dans C:\dev\OldStyleScale\Program.cs:ligne 11
       à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       à System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

Maybe there should be some kind of `suppressUpdate` too or something like this to actually end the game.

Windows 7 64b, MonoGame dev snapshot from 08/13/2016, win DirectX platform.

### PR DESCRIPTION
**Pull request by Jjagg**
As discussed in #5127 `Game.Exit` should not immediately dispose of the game window, but should set a flag and handle actual exiting and disposal at the end of the tick.
fixes #5127

I think this doesn't work for Android since it uses a [custom run loop](https://github.com/MonoGame/MonoGame/blob/7c3d6870a38f8a5e479e64d935d692f2610e1cda/MonoGame.Framework/Android/AndroidGamePlatform.cs#L105). @dellis1972 How should this be handled? 
Are there any other platforms that have their own run loop?

### CODE REVIEW

File: Test/Framework/GameTest.cs [hunk 1]
```diff
@@ -239,6 +168,70 @@ public void Fixed_time_step_skips_draw_when_update_is_slow ()
...
+        public class Misc
+        {
+            [Test]
+            public void ExitHappensAtEndOfTick()
+            {
+                // Exit called in Run
+                var g = new ExitTestGame();
+
+                // TODO this is not necessary for XNA, but MG crashes when no GDM is set and Run is called
+                new GraphicsDeviceManager(g);
```
Comment (Jjagg) [inline Test/Framework/GameTest.cs]: Yeah, I'll dig into that.

**Comment by tomspilman** [comment]
Thanks @Jjagg ... merging!

**Comment by Jjagg** [comment]
@tomspilman Like I said, I think this breaks Exit() for Android.

**Comment by tomspilman** [comment]
@Jjagg - Oh well...  @dellis1972 ???

**Comment by dellis1972** [comment]
not in the position to look at this atm sorry guys.

**Comment by tomspilman** [comment]
I guess it is broken for now then. :)
