### PR TITLE
Marshal microphone identifiers as UTF-8

### LINKED ISSUE #6529: System.ExecutionEngineException
I try to run application but get this error

monogame_bug

System.ExecutionEngineException
String conversion error: Illegal byte sequence encounted in the input.
at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStringAnsi(intptr)
at Microsoft.Xna.Framework.Audio.Microphone.PopulateCaptureDevices () [0x00081] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Microsoft.Xna.Framework.Audio.OpenALSoundController..ctor () [0x0003b] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Microsoft.Xna.Framework.Audio.OpenALSoundController.get_GetInstance () [0x00007] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Microsoft.Xna.Framework.SdlGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x000d2] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00000] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Microsoft.Xna.Framework.Game..ctor () [0x001fb] in <1b3500140e1c4909bb864bc920f14b3b>:0
at Terminal.Payment.UI.Game1..ctor () [0x00000] in /media/destructor/Documents/Projects/TestSistema/TestSistema/Game1.cs:19
at Terminal.Payment.UI.Program.Main () [0x00001] in /media/destructor/Documents/Projects/TestSistema/TestSistema/Program.cs:17 

Working directory
monogame_bug2

#### System Stats
- MonoGame 3.7 from Nuget
- Debian 9
- Mono 5.16
- .Net Framework is 4.7.1

#### What MonoGame platform are you using:
- DesktopGL

### PR DESCRIPTION
**Pull request by Jjagg**
Fixes #6529. 

~I didn't test this yet, hope it works like this.~
EDIT: this works on my machine

### CODE REVIEW

**Comment by Jjagg** [comment]
This was confirmed to fix #6529. Ready for merge IMO :)

**Comment by cra0zy** [comment]
@Jjagg There already is a method for converting pointers strings to UTF8, please use it instead: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/SDL/SDL2.cs#L55

PS. Feel free to fix `return ""` to `return string.Empty`

File: MonoGame.Framework/SDL/SDL2.cs [hunk 1]
```diff
@@ -52,16 +52,20 @@ private static IntPtr GetNativeLibrary()
     public static int Minor;
     public static int Patch;
 
-    private static unsafe string GetString(IntPtr handle)
+    public static unsafe string GetString(IntPtr handle)
     {
         if (handle == IntPtr.Zero)
-            return "";
+            return string.Empty;
```
Comment (Jjagg) [inline MonoGame.Framework/SDL/SDL2.cs]: @cra0zy I guess it would be more appropriate to return `null` here. I didn't change it because some code might depend on this behavior. Empty string is right only when `handle` points to `\0`.

**Comment by Jjagg** [comment]
@cra0zy Thanks, updated.

**Comment by cra0zy** [comment]
> EDIT: Android build failed because it doesn't have SDL. Could create a new `InteropHelpers` class or something and make a `Utf8ToString` method if that's preferable, but just reverted for now. I'm fine with either solution.

Yea yea, feel free to extract the function to some util class, when I added it we only needed it for SDL and I didn't expect it to be needed in other places.

**Comment by Jjagg** [comment]
@cra0zy Done!

File: MonoGame.Framework/Audio/Microphone.OpenAL.cs [hunk 2]
```diff
@@ -52,18 +53,26 @@ internal static void PopulateCaptureDevices()
...
+            // Marshal native UTF-8 character array to .NET string
+            // The native string is a null-char separated list of known capture device specifiers ending with an empty string
+
+            while (true)
             {  
-                Microphone microphone = new Microphone(deviceIdentifier);
-                _allMicrophones.Add(microphone);                
+                var deviceIdentifier = InteropHelpers.Utf8ToString(deviceList);
+
+                if (deviceIdentifier == string.Empty)
```
Comment (cra0zy) [inline MonoGame.Framework/Audio/Microphone.OpenAL.cs]: Use `string.IsNullOrEmpty`

File: MonoGame.Framework/Utilities/InteropHelpers.cs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+using System;
+using System.Runtime.InteropServices;
+using System.Text;
+
+namespace MonoGame.Utilities
+{
+    internal static class InteropHelpers
+    {
+        // Convert a pointer to a Utf8 null-terminated string to a .NET System.String
```
Comment (cra0zy) [inline MonoGame.Framework/Utilities/InteropHelpers.cs]: If you want to add a comment for what the method does, make it a documentation comment so its seen from intellisense.
