### PR TITLE
Fix IndexBuffer reflection issue

### LINKED ISSUE #8699: Exception when creating a new IndexBuffer (v3.8.3)
### Issue description

After updating my project from MonoGame **v3.8.2.1105** to **v3.8.3** (from the NuGet package), the following line throws an exception :

```csharp
IndexBuffer buffer = new IndexBuffer(GraphicsDevice, typeof(short), 12, BufferUsage.None);
```

Exception thrown :
```
`System.ArgumentException: 'Type 'System.RuntimeType' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.'`
```

### Steps to reproduce

Put this line in a blank MonoGame project (in the `Game1.LoadContent()` method) :
```csharp
IndexBuffer buffer = new IndexBuffer(GraphicsDevice, typeof(short), 12, BufferUsage.None);
```

 This line works well in **v3.8.2.1105**, but it throws the exception in **v3.8.3**.

### Technical infos

**MonoGame version :** 3.8.3
**Project version :** `net9.0-windows`
**Project type :** MonoGame Windows Desktop Application (mgwindowsdx)
**Operating System :** Windows 11

### PR DESCRIPTION
**Pull request by ThomasFOG**
Fixes #8699

Also adds a test to avoid regression.

### CODE REVIEW

**Review by SimonDarksideJ — APPROVED** [review]

File: Tests/Framework/Graphics/IndexBufferTest.cs [hunk 1]
```diff
@@ -90,5 +90,13 @@ public void NullDeviceShouldThrowArgumentNullException()
             });
             GC.GetTotalMemory(true); // collect uninitialized IndexBuffer
         }
+
+        [Test]
+        [RunOnUI]
+        public void TypedConstructorShouldWork()
+        {
+            var indexBuffer = new IndexBuffer(gd, typeof(short), 12, BufferUsage.None);
```
Comment (dellis1972) [inline Tests/Framework/Graphics/IndexBufferTest.cs:98]: I would have added a test for `typeof(int)` as well 🤷

Comment (ThomasFOG) [reply Tests/Framework/Graphics/IndexBufferTest.cs:98]: Good call.
