### PR TITLE
Fixing memcpy Bug in MGG_Buffer_GetData

### LINKED ISSUE #9277: Target Buffer Overflow in Buffer_GetData
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame.Framework.Native 3.8.5-preview.4
Also current `develop` branch as of creation of this issue.

### Which MonoGame platform are you using?

WindowsDX12

### Operating System

Windows 11

### Description

This is an issue in the native DX12 backend.

There is a bug in `Buffer_GetData` where we cause target memory location to be overrun during memcpy().

### Steps to Reproduce

Attempt something like this:

```cs
var stride = part.VertexBuffer.VertexDeclaration.VertexStride;    //36
part.VertexBuffer.GetData(
    part.VertexOffset * stride,
    vertices,
    0,
    part.NumVertices,
    stride);
```
Where `vertices` is an array of `Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture`, whose size is 32.

### Minimal Example Repo

_No response_

### Expected Behavior

Buffer_GetData should correctly copy in steps, ignore padding, and the game should run.

### Resulting Behavior

The game crashes with this error:
```
Fatal error.
0xC0000005
   at MonoGame.Interop.MGG.Buffer_GetData(MonoGame.Interop.MGG_GraphicsDevice*, MonoGame.Interop.MGG_Buffer*, Int32, Byte*, Int32, Int32, Int32)
   at Microsoft.Xna.Framework.Graphics.VertexBuffer.PlatformGetData[[Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture, MonoGame.Framework, Version=3.8.5.0, Culture=neutral, PublicKeyToken=null]](Int32, Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture[], Int32, Int32, Int32)
   at Sin3D.Model3D.ExtractTransformedTriangles(Microsoft.Xna.Framework.Matrix ByRef)
   at FooBar.Core.Components.Level.LoadContent()
   at FooBar.Core.FooBarGame.StartNewLevel()
   at FooBar.Core.Gui.MainMenuWindow.<.ctor>b__20_0(System.Object, System.EventArgs)
   at Gum.Wireframe.InteractiveGue.DoUiActivityRecursively(Gum.Wireframe.ICursor, Gum.Wireframe.HandledActions, Gum.Wireframe.GraphicalUiElement, RenderingLibrary.Graphics.Layer)
   at Gum.Wireframe.InteractiveGue.DoUiActivityRecursively(Gum.Wireframe.ICursor, Gum.Wireframe.HandledActions, Gum.Wireframe.GraphicalUiElement, RenderingLibrary.Graphics.Layer)
   at Gum.Wireframe.InteractiveGue.DoUiActivityRecursively(Gum.Wireframe.ICursor, Gum.Wireframe.HandledActions, Gum.Wireframe.GraphicalUiElement, RenderingLibrary.Graphics.Layer)
   at Gum.Wireframe.GueInteractiveExtensionMethods.DoUiActivityRecursively(System.Collections.Generic.IList`1<Gum.Wireframe.GraphicalUiElement>, Gum.Wireframe.ICursor, Gum.Wireframe.IInputReceiverKeyboard, Double)
   at Gum.Forms.FormsUtilities.Update(Microsoft.Xna.Framework.Game, Microsoft.Xna.Framework.GameTime, System.Collections.Generic.IEnumerable`1<Gum.Wireframe.GraphicalUiElement>)
   at MonoGameGum.GumService.Update(Microsoft.Xna.Framework.GameTime, System.Collections.Generic.IEnumerable`1<Gum.Wireframe.GraphicalUiElement>)
   at FooBar.Core.FooBarGame.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.NativeGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior)
   at Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Program.Main(System.String[])
   at Program.<Main>(System.String[])
```

### Files

_No response_

### PR DESCRIPTION
**Pull request by uygary**
We have a check that compares `dataStride` against itself where it should be comparing it against `dataBytes`.

Fixes #9277

### Description of Change

1. We replace the `if (dataStride == dataStride)` check with `if (dataBytes == dataStride)` to fix the bug.
2. I've also added a `dataBytes < dataStride` check, but I'm not sure if it makes sense. As in whether I'm being paranoid, or it's better safe than sorry. I simply don't know the use-cases, so I'm not sure if it could possibly be the target that has padding.
3. I've added the same check to the Vulkan backend too, so let me know if it makes sense to keep them or not.
4. I've also added a `DX::ThrowIfFailed` check since `Allocator::CreateResource` returns `HRESULT`, but I'm not sure whether it's actually useful or not.

### Contributor Declaration

- [x] I certify that no LLM's were used to generate any code or documentation in this contribution.

### CODE REVIEW

**Review by tomspilman — APPROVED** [review]

**Comment by tomspilman** [comment]
This is great... thanks @uygary

**Comment by uygary** [comment]
So I take it you don't think the `dataBytes < dataStride` check is redundant @tomspilman ?
I'm only asking for my own education. Because I'm not really that familiar with where and how the padding usually occurs, or in which direction we may use this method.

File: native/monogame/directx12/MGG_DX12.cpp [hunk 1]
```diff
@@ -1361,13 +1363,19 @@ void MGG_Buffer_GetData(MGG_GraphicsDevice* device, MGG_Buffer* buffer, mgint of
...
 	DX::ThrowIfFailed(intermediateBuffer->Map(0, nullptr, reinterpret_cast<void**>(&pSourceDataBegin)));
-	if (dataStride == dataStride)
+	if (dataStride == dataBytes)
+	{
 		memcpy(data, pSourceDataBegin, dataStride * dataCount);
-	else {
+	}
+	else
+	{
+		auto bytesToCopy = dataBytes < dataStride ? dataBytes : dataStride;
```
Comment (tomspilman) [inline native/monogame/directx12/MGG_DX12.cpp:1372]: So what this does if you have padded data...say 3 bytes of data, but the stride is 4... it copies 3 bytes then steps 4 bytes.  If it is equal or *greater* then it clamps it to the stride size.  So it just protecting against a weird large `dataBytes` size.

@uygary

Comment (uygary) [reply native/monogame/directx12/MGG_DX12.cpp:1372]: Exactly, but there's more to it now with the `dataBytes < dataStride` check I've added.
We already guard against the case where `dataBytes` is **greater** than `dataStride` without this check, because memcopy is clamped at `dataStride`.

With this check, we also prevent copying over the padding if it is in the source. Because that would overflow the struct (`dataBytes` number of bytes) in the target when `dataBytes` is **smaller** than `dataStride`.
Overflowing in the initial copies is likely wasteful but fine, since the next struct will be overwritten from scratch durring the next memcopy call at each iteration.

But that's until we hit the last struct.
At that last copy operation, it would exceed the actual end of the target buffer, and overwrite a memory area that doesn't belong to the target buffer.

I just wasn't sure if this was a realistic case to guard against in the world of CPU/GPU interaction, which is why I wanted your feedback on whether you think this `dataBytes < dataStride` check is good or redundant.

@tomspilman

Comment (tomspilman) [reply native/monogame/directx12/MGG_DX12.cpp:1372]: > But at that last copy operation, it would exceed the actual end of the target buffer, and overwrite memory.

It is possible.... and the tiny cost of the extra check is worth some more safety.

Comment (uygary) [reply native/monogame/directx12/MGG_DX12.cpp:1372]: Thanks!
