### PR TITLE
Increasing HttpClient Timeout for UploadArtifacts Task

### LINKED ISSUE #9288: UploadArtifacts Task Occasionally Times-out
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### Description

The `UploadArtifacts` task times out on random builds in the CI/CD pipeline.
We should look into increasing the timeout value.

An example [is here](https://productionresultssa16.blob.core.windows.net/actions-results/87118a55-ad25-41bb-b13d-0b1faee8ce82/workflow-job-run-d1cc4714-62fb-5527-a405-7d51b243a29a/logs/job/job-logs.txt?rsct=text%2Fplain&se=2026-04-17T16%3A10%3A19Z&sig=ZmsuSdBl5f3jE%2F7%2FZ4GufCH7wIF9OzqOPwiFfx1o69g%3D&ske=2026-04-17T19%3A48%3A25Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2026-04-17T15%3A48%3A25Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2026-04-17T16%3A00%3A14Z&sv=2025-11-05):
```
Run dotnet run --project build/Build.csproj -- --target=UploadArtifacts
/Users/runner/.dotnet/sdk/9.0.307/Microsoft.Common.CurrentVersion.targets(2433,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. PE image does not have metadata. PE image does not have metadata. [/Users/runner/work/MonoGame/MonoGame/build/Build.csproj]
Version: 3.8.4.3683-develop
RepositoryUrl: https://github.com/MonoGame/MonoGame
BuildConfiguration: Release

========================================
An error occurred when executing task 'UploadArtifacts'.
UploadArtifacts
========================================

Task                          Duration            Status              
----------------------------------------------------------------------
UploadArtifacts               00:03:05.6334900    Failed              
----------------------------------------------------------------------
Total:                        00:03:05.6334900                        
Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Error: Process completed with exit code 255.
```

### PR DESCRIPTION
**Pull request by uygary**
Increasing default `HttpClient.Timeout` to 2 minutes, and making it configurable in the Build tool.

Fixes #9288

### Description of Change

- Explicitly registered a factory function for Cake to retrieve `HttpClient` instances.
It overrides the default 100s timeout value with 2m.
This is also configurable via a `HTTPCLIENT_TIMEOUT` env variable.
- Also added a `TestTimeoutTask` just to test that this works.

### Contributor Declaration

- [x] I certify that no LLM's were used to generate any code or documentation in this contribution.

### CODE REVIEW

**Comment by uygary** [comment]
This timeout keeps happening frequently.
Here's a recent example from this very PR, right before I force-pushed the rebased branch just now:
https://github.com/MonoGame/MonoGame/actions/runs/24521871193/job/71822296804?pr=9290

And here are 2 more that just happened on another PR:
https://github.com/MonoGame/MonoGame/actions/runs/24579768428/job/71874433878?pr=9280
https://github.com/MonoGame/MonoGame/actions/runs/24579768428/job/71874433911?pr=9280

@dellis1972 do you think this looks good to merge?

File: build/DeployTasks/TestTimeoutTask.cs [hunk 1]
```diff
@@ -0,0 +1,34 @@
+namespace BuildScripts
+{
+    [TaskName("Test HttpClient.Timeout")]
+    public sealed class TestTimeoutTask : FrostingTask<BuildContext>
```
Comment (dellis1972) [inline build/DeployTasks/TestTimeoutTask.cs]: This task does not seem to be used?

Comment (uygary) [reply build/DeployTasks/TestTimeoutTask.cs]: It's not. I've added it just to test the change locally with:
`dotnet run --project build/Build.csproj --target="Test HttpClient.Timeout"`

I figured I'd leave it in in case someone needs it to test this themselves, or if you folks ever want to plug this task in in order to log the current timeout value in the pipeline.

Comment (uygary) [reply build/DeployTasks/TestTimeoutTask.cs]: The change in the IOC registration/service setup is the only bit that functionally matters to resolve the issue.

Comment (dellis1972) [reply build/DeployTasks/TestTimeoutTask.cs]: Not sure we need this. We should however, add a `context.Log` to the code in the Program.cs to log what timeout is actually being used . Probably at https://github.com/MonoGame/MonoGame/pull/9290/changes#diff-5f44977b35aaf0b949b3e4ca9d6af26b6fb5ffd52f2c8fd9a5cf60e4a1080b5cR27

Comment (uygary) [reply build/DeployTasks/TestTimeoutTask.cs]: I don't think we even have the context there.
But I've added the log into `UploadArtifactsTask` itself. It will appear like this at the beginning of the task logs:
```
========================================
UploadArtifacts
========================================
HttpClient.Timeout is set at: 120 seconds.

```

Comment (uygary) [reply build/DeployTasks/TestTimeoutTask.cs]: From this very build:
image

**Review by dellis1972 — APPROVED** [review]
