### PR TITLE
[Native] WindowsDX12 fixes #2

### LINKED ISSUE #9021: WindowsDX12 subsequent SetRenderTarget not working
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

v3.8.5-develop.11

### Which MonoGame platform are you using?

WindowsDX12

### Operating System

Windows

### Description

Testing on the latest WindowsDX12.

If you call `SetRenderTarget` on a render target you created then subsequent calls to `SetRenderTarget` will fail.

For example:
`
            GraphicsDevice.SetRenderTargets(_renderTarget1);
            GraphicsDevice.Clear(Color.Red);

            _spriteBatch.Begin();
            _spriteBatch.Draw(_whiteTexture, new Rectangle(0, 0, 32, 32), Color.Blue);
            _spriteBatch.End();

            GraphicsDevice.SetRenderTarget(null);
            GraphicsDevice.Clear(Color.Black);

            _spriteBatch.Begin();
            _spriteBatch.Draw(_renderTarget1, _renderTarget1.Bounds, Color.White);
            _spriteBatch.End();
`

The final `_spriteBatch.End()` results in the error `Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

https://github.com/MonoGame/MonoGame/blob/94b1033b44d6b4d98420002d1577b7b262db9930/MonoGame.Framework/Platform/Native/GraphicsDevice.Native.cs#L450

I also tried a `SaveAsPng` on the `_renderTarget1` and it's just saving a blank image.

### Steps to Reproduce

1. Create a render target
2. Draw to the render target
3. Switch to a new render target
4. Draw to that render target

### Minimal Example Repo

https://github.com/arosolino/hit-start-monogame/tree/main/issues/windowsdx12-multiple-rts

### Expected Behavior

Should draw to the first render target and the set a new render target

### Resulting Behavior

Does not allow using a new render target

### Files

_No response_

### PR DESCRIPTION
**Pull request by arosolino**
Several fixes for getting WindowsDX working.

This is working off PR #9023

1. Fixed a bug where switching from multiple render targets back to a single render target wasn't properly handled. https://github.com/MonoGame/MonoGame/pull/9031/commits/6027892d7f73a12cd54822c28e2f5d5491f1e18b
2. Creating/setting a custom render target was never fully implemented. Custom render target is now created along with it's depth texture. Fixes #9021 https://github.com/MonoGame/MonoGame/pull/9031/commits/6027892d7f73a12cd54822c28e2f5d5491f1e18b
4. Disposing of textures was not calling `FreeDescriptors` resulting in an eventual crash. https://github.com/MonoGame/MonoGame/pull/9031/commits/6027892d7f73a12cd54822c28e2f5d5491f1e18b
5. `MGG_Buffer_SetData` was not using the correct signature. Going to need more work. https://github.com/MonoGame/MonoGame/pull/9031/commits/6027892d7f73a12cd54822c28e2f5d5491f1e18b
6. Fixed bug where a buffer remains on the free list when it doesn't match the exact size. a04b28103b6d207ee0fe9e4813606c38b38f98a1

### CODE REVIEW

File: native/monogame/directx12/MGG_DX12.cpp [hunk 1]
```diff
@@ -1382,7 +1417,18 @@ MGG_Texture* MGG_RenderTarget_Create(
...
 	auto texture = new MGG_Texture();
+
 	texture->format = format;
+	texture->texture = new Texture(SurfaceType::RenderTarget, TextureDimension::Texture2D, width, height, mipmaps, format);
+	texture->texture->Create(device->resources);
+
+	if (depthFormat != MGDepthFormat::None)
+	{
+		texture->depthTexture = new Texture(width, height, depthFormat);
+		//if (multiSampleCount > 1)
```
Comment (dellis1972) [inline native/monogame/directx12/MGG_DX12.cpp]: Is this commented code needed?

Comment (arosolino) [reply native/monogame/directx12/MGG_DX12.cpp]: It's not. I was just doing similar as the other depth texture being created and it seems like there was more still to be done.
https://github.com/MonoGame/MonoGame/blob/4fb05d4bfd3c5c3f5a45d89a596b8bfb4135c53c/native/monogame/directx12/MGG_DX12.cpp#L466

At the moment I am just trying to see if I can get my game up and running, but of course willing to help assist and make any changes you guys need.

**Comment by arosolino** [comment]
@tomspilman There is a major bug where a buffer remains on the free list when it doesn't match the exact size.

Not being removed from the free list on this line:
https://github.com/MonoGame/MonoGame/blob/4fb05d4bfd3c5c3f5a45d89a596b8bfb4135c53c/native/monogame/directx12/MGG_DX12.cpp#L1161

I supplied a fix for now but I noticed that Vulkan takes a different approach to the the free, pending, discarded by using a linked list. Since we are trying to accomplish the same goal on both of these platforms which approach should be taken here?

DX12: MGDX_BufferDiscard
https://github.com/MonoGame/MonoGame/blob/4fb05d4bfd3c5c3f5a45d89a596b8bfb4135c53c/native/monogame/directx12/MGG_DX12.cpp#L1121-L1163

Vulkan: MGVK_BufferDiscard
https://github.com/MonoGame/MonoGame/blob/4fb05d4bfd3c5c3f5a45d89a596b8bfb4135c53c/native/monogame/vulkan/MGG_Vulkan.cpp#L4191-L4242

File: build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs [hunk 2]
```diff
@@ -25,7 +25,6 @@ public override void Run(BuildContext context)
         switch (context.Environment.Platform.Family)
         {
             case PlatformFamily.Windows:
-                configureArgs.Append("-A x64");
                 configureArgs.Append("-D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded");
```
Comment (tomspilman) [inline build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs:29]: @ThomasFOG @harry-cpp this look right to you?

**Review by tomspilman — DISMISSED** [review]

File: build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs (hunk 2 above)
Comment (SimonDarksideJ) [reply build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs:29]: Can we revert this change @arosolino , unless there is a specific reason you thought to include it?

Comment (arosolino) [reply build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs:29]: This was from PR #9023

I can remove it but @sepcnt will need to answer that for you all.

Comment (sepcnt) [reply build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs:29]: Visual Studio 2026 is no longer compatible with this option.

Comment (dellis1972) [reply build/BuildFrameworksTasks/BuildNativeDependenciesTask.cs:29]: @arosolino I think so we can get these changes in , lets revert that change for now. VS 2026 is still in preview so lets not change the build system just yet.

**Review by tomspilman — APPROVED** [review]
