### PR TITLE
Reduce garbage from TextInput

### LINKED ISSUE #6360: Each keystroke produces some garbage
#### Symptoms:
Each keystroke produces garbage. If you hold the key, the garbage will seem to be generated each time a repeated keystroke is reported by the OS.

#### How to reproduce:
Download the attached .NET Core 2.1 project that contains some diagnostic code: https://phobia.games/experiments/Game1Core.zip

1. Run the project.
2. It should report no allocations per frame.
3. Press (and hold) any alphanumeric key, the program should report some allocations.

#### Possible cause:
https://github.com/MonoGame/MonoGame/blob/b1a49e4ae60eaf62169d08c791d4f9a913b495b3/MonoGame.Framework/SDL/SDLGameWindow.cs#L302

That line creates an object each time a system's key stroke event is handled, regardless of whether the programmer actually utilizes the `Window.TextInput` event or not.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

### PR DESCRIPTION
**Pull request by mrhelmut**
Hey there,

This is a proposal to start addressing #6360.

It removes the string manipulations and decodes each UTF8 characters individually and sends them to the event handler.
It also skips the event processing if there is no event handler attached to ```GameWindow.TextInput```.

This should:
- remove all garbage if ```TextInput``` isn't used when pressing keys (which I believe is the most important fix here)
- greatly reduce garbage when actually using ```TextInput```

There is still some garbage generated from this line when attaching an handler to ```TextInput```:
https://github.com/MonoGame/MonoGame/blob/b1a49e4ae60eaf62169d08c791d4f9a913b495b3/MonoGame.Framework/SDL/SDLGameWindow.cs#L302

We will have to figure out (in another PR?) what to do with event args types.

Also, it should be noted that this PR comes with a limitation (note that the original code also has this limitation): it doesn't support UTF8 characters that are encoded on more than 2 bytes (because ```TextInputEventArgs``` is limited by the ```char``` type). Chinese, Japanese, and Korean won't be supported.

This should be addressed in another PR I guess (at the same time as addressing the event args type?).

Partly fixes #6360

### CODE REVIEW

File: MonoGame.Framework/GameWindow.cs [hunk 1]
```diff
@@ -102,6 +102,8 @@ protected GameWindow()
 		/// This event is only supported on the Windows DirectX, Windows OpenGL and Linux platforms.
 		/// </remarks>
 		public event EventHandler<TextInputEventArgs> TextInput;
+
+        public bool IsTextInputHandled { get { return TextInput != null; } }
```
Comment (cra0zy) [inline MonoGame.Framework/GameWindow.cs]: Shouldn't this be internal?

Comment (mrhelmut) [reply MonoGame.Framework/GameWindow.cs]: You are right, I've updated this.

**Comment by cra0zy** [comment]
Thanks @mrhelmut , merging!
