### PR TITLE
Stencil Handling in RenderTarget2D

### LINKED ISSUE #9279: Stencil Handling in WindowsDX12 Crashes the Game When RenderTarget2D is Created
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame.Framework.Native 3.8.5-preview.4
Also current `develop` branch as of creation of this issue.

### Which MonoGame platform are you using?

WindowsDX12

### Operating System

Windows 11

### Description

This is an issue in the native DX12 backend.

At first glance, this looked somewhat like related to #9217 but I don't think it is, since that one's specific to Vulkan on Linux whereas this one's specific to DX12.
When a `RenderTarget2D` is created with `DepthFormat.Depth24Stencil8`, the game crashes on DX12. When `DepthFormat.Depth24` is used, it runs fine.
The behaviour is specific to DX12, and the same code run fine with `DepthFormat.Depth24Stencil8` on the Vulkan backend.

Also, once the crash is resolved, I realized the stencil mask wasn't applied in DX12. The `ReferenceStencil` value was being ignored.

Looking into the stack trace, it looks like this is the flow:

1. We call into [RenderTarget_Create](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/MonoGame.Framework/Platform/Native/Graphics.Interop.cs#L355-L367).
2. RenderTarget_Create P/Invokes [MGG_RenderTarget_Create](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/MGG_DX12.cpp#L1410-L1445)
3. `depthFormat` appears to be only relevant [where we create the texture](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/MGG_DX12.cpp#L1438-L1442).
4. In the `Texture` ctor we use, format argument is referenced in 2 places:
First it's assigned to `m_depthFormat`.
Then we populate `m_desc` using [CD3DX12_RESOURCE_DESC::Tex2D](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/Texture.cpp#L63) based on that argument.
6. That actually uses [DepthFormatToDXGI_FORMAT](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/GraphicsEnums.h#L49-L54) to map it to a `DXGI_FORMAT`.Here I noticed that both `Depth24` and `Depth24Stencil8` are mapped to `DXGI_FORMAT_D24_UNORM_S8_UINT`.
I'm not sure whether this is correct or not, but it can't be the source of the bug, since both values end up being mapped to the same format.
6. What I've also noticed is that the `m_depthFormat` is later used [in the Create method](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/Texture.cpp#L153-L154) that `MGG_RenderTarget_Create` calls into immediately after the ctor.
7. Here we use `DepthFormatToSRV` to [map m_depthFormat](https://github.com/MonoGame/MonoGame/blob/9e3a2dfd3f18a48924284d6d70eb019bcb40c72b/native/monogame/directx12/GraphicsEnums.h#L56-L61) to `DXGI_FORMAT` again.
This time we map `Depth24` to `DXGI_FORMAT_R24_UNORM_X8_TYPELESS` and `Depth24Stencil8` to `DXGI_FORMAT_R24G8_TYPELESS`.

At this point I'm kind of sure this is where the bug is since here's where the two `DepthFormat` values differentiate.
I basically suspect the `DXGI_FORMAT_R24G8_TYPELESS` mapping is wrong, but at the same time, I don't understand what the comment here actually means:
>// stencil accessed by G channel

I'm doing my research and and my testing with the hope of understanding the bug and sending a PR, but I'd love some clear explanation about this comment.

### Steps to Reproduce

Try to have the game render to a RenderTarget2D instead of using the back-buffer directly:

```cs
new RenderTarget2D(graphicsDevice,
            width,
            height,
            false,
            SurfaceFormat.Color,
            DepthFormat.Depth24Stencil8)
```

### Minimal Example Repo

_No response_

### Expected Behavior

A new RenderTarget2D is instantiated, and the game runs happily ever after.

### Resulting Behavior

The process crashes with nothing useful in the console:
```
X:\BLAH\FooBar\src\FooBar\FooBar.DesktopDX12\bin\Debug\net10.0\FooBar.exe (process 114848) exited with code -1 (0xffffffff).

```

And when debugged, a stack trace pointing at the `RenderTarget_Create` P/Invoke appears on the native exception:
```
System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=MonoGame.Framework
  StackTrace:
   at MonoGame.Interop.MGG.RenderTarget_Create(MGG_GraphicsDevice* device, TextureType type, SurfaceFormat format, Int32 width, Int32 height, Int32 depth, Int32 mipmaps, Int32 slices, DepthFormat depthFormat, Int32 multiSampleCount, RenderTargetUsage usage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat)
   at Sin3D.RenderLayer..ctor(String name, RenderLayerType layerType, Int32 drawOrder, GraphicsDevice graphicsDevice, Int32 width, Int32 height) in X:\BLAH\FooBar\src\Sin3d\src\Sin3D\RenderLayer.cs:line 47
   at FooBar.Core.FooBarGame.SetRenderLayers() in X:\BLAH\FooBar\src\FooBar\FooBar.Core\FooBarGame.cs:line 682
   at FooBar.Core.FooBarGame.LoadContent() in X:\BLAH\FooBar\src\FooBar\FooBar.Core\FooBarGame.cs:line 271
   at FooBar.Core.FooBarGame.Initialize() in X:\BLAH\FooBar\src\FooBar\FooBar.Core\FooBarGame.cs:line 167
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>d__0.MoveNext() in X:\BLAH\FooBar\src\FooBar\FooBar.DesktopDX12\Program.cs:line 47
   at Program.<Main>d__0.MoveNext() in X:\BLAH\FooBar\src\FooBar\FooBar.DesktopDX12\Program.cs:line 56
```

### Files

_No response_

### PR DESCRIPTION
**Pull request by uygary**
Attempting to fix a DX12 bug that turned into 2 bugs during my testing:

1. `DepthFormat.Depth24Stencil8` handling was wrong in `Texture::Create()`. This causes `RenderTarget2D` ctor to throw and crash the game.
2. `ReferenceStencil` value was being ignored, which prevented stencil masks from working.

Fixes #9279

### Description of Change

- Changing `DepthFormatToSRV` mapping to return `DXGI_FORMAT_R24_UNORM_X8_TYPELESS` instead of `DXGI_FORMAT_R24G8_TYPELESS` for `Depth24Stencil8`.
- We store `ReferenceStencil` in `MGG_DepthStencilState`.
- We make sure `ReferenceStencil` is set for each frame in `MGG_GraphicsDevice_SetDepthStencilState`.

### Contributor Declaration

- [x] I certify that no LLM's were used to generate any code or documentation in this contribution.

### CODE REVIEW

File: native/monogame/directx12/GraphicsEnums.h [hunk 1]
```diff
@@ -56,8 +56,15 @@ static constexpr DXGI_FORMAT DepthFormatToDXGI_FORMAT[] = {
 static constexpr DXGI_FORMAT DepthFormatToSRV[] = {
     DXGI_FORMAT_UNKNOWN,
     DXGI_FORMAT_R16_UNORM,
-    DXGI_FORMAT_R24_UNORM_X8_TYPELESS, // stencil typeless, not readable in shader since it shouldn't be here in the first place
-    DXGI_FORMAT_R24G8_TYPELESS // stencil accessed by G channel
+    DXGI_FORMAT_R24_UNORM_X8_TYPELESS,  // For Depth24: Depth only. Stencil is typeless. ("stencil typeless, not readable in shader since it shouldn't be here in the first place")
+    DXGI_FORMAT_R24_UNORM_X8_TYPELESS   // For Depth24Stencil8: There is stencil, but SRV reads only depth. Stencil is typeless, and not accessible by shader via this view. (I'm not sure what the original comment means: "stencil accessed by G channel")
+};
+
+static constexpr DXGI_FORMAT DepthFormatToStencilSRV[] = {
```
Comment (uygary) [inline native/monogame/directx12/GraphicsEnums.h]: Do we need something like this to expose a separate SRV for stencil data?
How are we gonna use this?

Comment (tomspilman) [reply native/monogame/directx12/GraphicsEnums.h]: So the XNA 4.0 API could not read from a depth buffer at all... z depth or stencil.

For now i would not add this as we have no way to bind just the depth-stencil buffer to a shader anyway.

File: native/monogame/directx12/GraphicsEnums.h [hunk 2]
```diff
@@ -56,8 +56,15 @@ static constexpr DXGI_FORMAT DepthFormatToDXGI_FORMAT[] = {
 static constexpr DXGI_FORMAT DepthFormatToSRV[] = {
     DXGI_FORMAT_UNKNOWN,
     DXGI_FORMAT_R16_UNORM,
-    DXGI_FORMAT_R24_UNORM_X8_TYPELESS, // stencil typeless, not readable in shader since it shouldn't be here in the first place
-    DXGI_FORMAT_R24G8_TYPELESS // stencil accessed by G channel
```
Comment (tomspilman) [inline native/monogame/directx12/GraphicsEnums.h:60]: Actually seems like both Depth24 and Depth24Stencil8 should be `DXGI_FORMAT_R24G8_TYPELESS `... as there is no only 24bit format available.

Did you see an issue using DXGI_FORMAT_R24G8_TYPELESS?

File: native/monogame/directx12/GraphicsEnums.h (hunk 1 above)
Comment (uygary) [reply native/monogame/directx12/GraphicsEnums.h]: I've removed `DepthFormatToStencilSRV`.

File: native/monogame/directx12/GraphicsEnums.h (hunk 2 above)
Comment (uygary) [reply native/monogame/directx12/GraphicsEnums.h:60]: Apologies for the lot of conversation on the issue itself. Maybe I should've put all my comments in the PR instead. But I started commenting there before I even had a PR, so kept the conversation there.

Basically, yes, `DXGI_FORMAT_R24G8_TYPELESS` immediately crashes the app, because apparently [the SRV cannot contain anything `_TYPLESS`](https://stackoverflow.com/questions/38933565/which-format-to-use-for-a-shader-resource-view-into-depth-stencil-buffer-resourc#:~:text=When%20viewing%20a%20resource%2C%20the,typed%20format%20for%20the%20view.) in DX12.
The entire explanation is here on the issue: https://github.com/MonoGame/MonoGame/issues/9279

Comment (tomspilman) [reply native/monogame/directx12/GraphicsEnums.h:60]: Ok yea.... that makes sense then.

I say remove most the comments here, just do:

```
DXGI_FORMAT_R24_UNORM_X8_TYPELESS,  // There is no 24bit only format for depth.
DXGI_FORMAT_R24_UNORM_X8_TYPELESS, 
```

Comment (uygary) [reply native/monogame/directx12/GraphicsEnums.h:60]: Done.

**Review by tomspilman — APPROVED** [review]
