### PR TITLE
Fixed GLDesktop PlatformStop() resolving issue #7372

### LINKED ISSUE #7372: Bug in SoundEffectInstance.Pause on Windows
If you Pause() a SoundEffectInstance, and then Stop() it while it's paused,  you can never pause it again.   

If you look at the code in SoundEffectInstance.OpenAL.cs you'll see that neither `PlatformStop()` nor `PlatformPlay()` reset the `pauseCount` and a `pauseCount` > 0 will prevent you from actually pausing the sound again in `PlatformPause()`, no matter how many times you stop or restart it.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
DesktopGL

### PR DESCRIPTION
**Pull request by JacksonDorsett**
Bug addressed: When using DesktopGL the pause counter field is not reset when stop is called.

In SoundEffectInstance.PlatformStop() on the OpenAL platform. pauseCounter is set to 0 if its value is greater than 0. 

Fixes #7372.

### CODE REVIEW

**Review by mrhelmut — APPROVED** [review]

**Comment by initram** [comment]
Should the order of the calls i the test not be: play, pause, stop, play?

File: Tests/Framework/Audio/SoundEffectInstanceTest.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            // Necessary to get audio initialised
+            FrameworkDispatcher.Update();
+        }
+
+        /// <summary>
+        /// Unit test for issue #7372 where the Sound effects instance does not play after Play()
+        /// is called after calling Pause(), Stop().
+        /// </summary>
+        [Test]
+#if !DESKTOPGL
```
Comment (Jjagg) [inline Tests/Framework/Audio/SoundEffectInstanceTest.cs:29]: No need to exclude this for other platforms, so this directive can be removed.

**Review by Jjagg — CHANGES_REQUESTED** [review]
Thanks for the PR :)

File: Tests/Framework/Audio/SoundEffectInstanceTest.cs (hunk 1 above)
Comment (JacksonDorsett) [reply Tests/Framework/Audio/SoundEffectInstanceTest.cs:29]: I originally intended to make it a test for both platforms but when I tried testing the DirectX Audio, its implementation sets the state to stop rather than pause. 
I noticed that after additional testing that the Assert.AreEqual(SoundState.Stopped, instance) is runs to quickly after calling stop. This can be temporarily fixed by making the thread sleep for 10 ms before running the test, but it may be an indicator of additional bugs.

**Comment by JacksonDorsett** [comment]
The automated build may be broken since the last commit was a comment and it passed two more checks.

**Comment by Jjagg** [comment]
Yes, there's some issues on the build bots unrelated to this PR.

Thanks again!
This looks good to me, though we might hold off merging until we get the build bot fixed.

**Review by Jjagg — APPROVED** [review]

**Comment by mrhelmut** [comment]
Could you rebase your changes so that the build bot rechecks everything? Once it's all green, I'll proceed with merging it.

**Comment by mrhelmut** [comment]
@JacksonDorsett mind checking this PR for a rebase?

**Comment by mrhelmut** [comment]
I have manually run the test since the buildbot is down. We're good with this PR, thank you!
